<a href="https://colab.research.google.com/github/TejashreeDV/Atharvo-final-project/blob/main/Lasso_and_Ridge_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
#from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, RidgeCV
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing

In [ ]:
# Load the california housing dataset
data = fetch_california_housing()
X, y = data.data, data.target

In [ ]:
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
data.target_names

['MedHouseVal']

In [ ]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [ ]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
np.logspace(-6, 6, 13)

array([1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01,
       1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06])

In [ ]:
# Standardize the features (very important for regularization)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Lasso Regression with cross-validation to find the best alpha
lasso_cv = LassoCV(alphas=np.logspace(-6, 6, 13), cv=5)
lasso_cv.fit(X_train_scaled, y_train)
print("Best alpha for Lasso:", lasso_cv.alpha_)
print("Lasso Coefficients:", lasso_cv.coef_)

Best alpha for Lasso: 0.001
Lasso Coefficients: [ 0.84390401  0.12280902 -0.28584776  0.33457952 -0.         -0.04071854
 -0.8830857  -0.85715141]


In [ ]:


# Ridge Regression with cross-validation to find the best alpha
ridge_cv = RidgeCV(alphas=np.logspace(-6, 6, 13), cv=5)
ridge_cv.fit(X_train_scaled, y_train)

print("Best alpha for Ridge:", ridge_cv.alpha_)
print("Ridge Coefficients:", ridge_cv.coef_)

Best alpha for Ridge: 10.0
Ridge Coefficients: [ 8.48518990e-01  1.23000589e-01 -2.97069387e-01  3.45348512e-01
 -5.84614949e-04 -4.17408932e-02 -8.85416224e-01 -8.60056304e-01]


In [ ]:
# Evaluate the models
lasso_pred = lasso_cv.predict(X_test_scaled)
ridge_pred = ridge_cv.predict(X_test_scaled)

print("Lasso Test MSE:", mean_squared_error(y_test, lasso_pred))
print("Ridge Test MSE:", mean_squared_error(y_test, ridge_pred))

Lasso Test MSE: 0.5297443668521693
Ridge Test MSE: 0.5303396264055756
